server:
  port: 7901
  context-path: /project
spring:
  http:  
        encoding.charset: UTF-8  
        encoding.enable: true  
        encoding.force: true 
  mvc:  
    view:  
            prefix: /WEB-INF/jsp/  
            suffix: .jsp    
            static-path-pattern: /**
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/boot
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update

    
   